export const relation = {
  from: {
    dataset: 'overheidsorganisaties',
    name: 'A. C. L. Rutte',
    id: 'urn:hgid:overheidsorganisaties/129653',
    data: {
      sex: 'u',
      rank: [],
      titles: [],
      etitles: [],
      initials: ['A', 'C', 'L'],
      tussenv: [],
      firstnames: [],
      name: 'Rutte',
    },
    type: 'tnl:Person',
  },
  to: {
    type: 'tnl:Public',
    dataset: 'overheidsorganisaties',
    name: 'Amsterdam',
    data: {
      systemId: 45546,
      naam: 'Amsterdam',
      contactEmail: 'aW5mby5wc2NqQG1pbnZlbmoubmw=',
      parentId: 13254,
      type: 'overheidsorganisatie',
      postAdres: 'Postbus 20301; 2500 EH; Den Haag',
      bezoekAdres: '; ; ',
      internet: 'www.kinderbescherming.nl',
      emailadres: 'info@kinderbescherming.nl',
    },
    id: 'urn:hgid:overheidsorganisaties/45546',
  },
  type: 'tnl:advisor',
};
